# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKy6fNnW21Ijodzj2PVcv7VsNJQ-TEd_
"""

# This code prints a welcome message
print("Welcome to Python Programming!")
# This prints my name and course
print("Name: Kholoud")
print("Course: Python Programming")

student_name = "Alice"
age = 20
gpa = 3.75
subjects = ["Math", "Python", "Physics"]
student_info = {"id":101, "year"  :2}
skills = {"Python" , "SQL"}
is_enrolled = True
graduation_data = None

print(student_name, type(student_name))
print(age, type(age))
print(gpa, type(gpa))
print(subjects, type(subjects))
print(student_info, type(student_info))
print(skills, type(skills))
print(is_enrolled, type(is_enrolled))
print(graduation_data, type(graduation_data))



